# Generated by Django 2.1.4 on 2018-12-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181207_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='amount_requested',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
