# Generated by Django 2.1.4 on 2018-12-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userdata_session_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='sector',
            field=models.CharField(choices=[('Agri', 'Agriculture'), ('Fin', 'Finance'), ('Retail', 'Retail'), ('Med', 'Medical Research'), ('Infra', 'Infrastructure'), ('Oth', 'Others')], default='Oth', max_length=25),
        ),
    ]
