# Generated by Django 2.1.4 on 2018-12-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='tenure_months',
            new_name='tenure_years',
        ),
    ]
